---
- hosts: "{{ targetHost }}"
  become: yes
  gather_facts: yes
  tasks:
  - shell: pwd
  - copy: 
      src: ~/var/lib/jenkins/workspace 
      dest: /home/ec2-user
      owner: ec2-user
      group: ec2-user        
      mode: 0644
  
    
