---
- hosts: all
  become: yes
  gather_facts: false
  vars_file: ~/ec2.py
  tasks:
  - yum: name=flask state=latest
  - shell: cd /
  - copy: src=/var/lib/jenkins/workspace/flaskapp/* dest=/home/ec2-user
