---
- hosts: {{ targetHost}}
  vars:
    ansible_host_key_checking: false
    ansible_ssh_host_key_checking: false
  become: yes
  gather_facts: false
  tasks:
  - yum: name=flask state=latest
  - shell: cd /
  - copy: src=/var/lib/jenkins/workspace/flaskapp/* dest=/home/ec2-user
